version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  postgres:
    image: postgres:14
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: telegrambotsmarketplace/marketplace_backend
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - static:/backend_static
      - media:/app/media
  # frontend:
  #   image: telegrambotsmarketplace/marketplace_frontend
  #   env_file: .env
  #   command: cp -r /app/build/. /frontend_static/
  #   volumes:
  #     - static:/frontend_static
  nginx:
    image: telegrambotsmarketplace/marketplace_nginx
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/app/media
