# Generated by Django 4.2.5 on 2023-09-28 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("-created",),
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
