# Generated by Django 4.2.5 on 2023-09-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_added_ordering_in_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(verbose_name="стоимость"),
        ),
    ]
