# Generated by Django 4.2.5 on 2023-10-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_product_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="article",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="артикул",
            ),
        ),
    ]
