# Generated by Django 4.2.5 on 2023-10-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_product_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="article",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="артикул"
            ),
        ),
    ]
