# Generated by Django 4.2.5 on 2023-10-20 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0013_alter_order_options_alter_orderproductlist_options_and_more",
        ),
        ("products", "0013_alter_shoppingcart_options_and_more"),
    ]

    operations = []
