# Generated by Django 4.2.5 on 2023-10-23 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_alter_shoppingcart_options_and_more"),
        ("products", "0014_merge_20231020_1614"),
    ]

    operations = []
