# Generated by Django 4.2.5 on 2023-10-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_merge_20231023_1946"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="pay_method",
            field=models.CharField(
                blank=True,
                choices=[("card", "card"), ("sbp", "sbp")],
                max_length=4,
                null=True,
                verbose_name="Метод оплаты",
            ),
        ),
    ]
