# Generated by Django 4.2.5 on 2023-11-13 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0022_alter_review_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(
                max_length=500,
                validators=[django.core.validators.MinLengthValidator(6)],
                verbose_name="текст отзыва",
            ),
        ),
    ]
