# Generated by Django 4.2.5 on 2023-11-13 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0023_alter_product_name"),
        ("products", "0023_alter_review_text"),
    ]

    operations = []
