# Generated by Django 4.2.5 on 2023-12-18 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0025_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="background_color",
            field=models.CharField(
                blank=True, max_length=7, null=True, verbose_name="цвет фона"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.image",
                verbose_name="изображение категории",
            ),
        ),
    ]
