# Generated by Django 4.2.5 on 2023-12-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0026_category_background_color_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="video",
            field=models.URLField(
                blank=True, null=True, verbose_name="ссылка на видео"
            ),
        ),
    ]
