# Generated by Django 4.2.5 on 2023-12-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0027_alter_product_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_used",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="статус использования"
            ),
        ),
    ]
