# Generated by Django 4.2.5 on 2023-09-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_bayer",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_seller",
            field=models.BooleanField(default=False),
        ),
    ]
